version: 2

before:
  hooks:
    - go mod tidy

###
# Builds
###

nix:
  - url_template: "https://github.com/semx/helmtide/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    name: helmtide
    ids: [ helmtide ]

    homepage: https://helmtide.dev/
    description: "helmtide is a maintained fork of helmwave: release management for helm"
    license: "mit"

    # Repository to push the generated files to.
    repository:
      owner: semx
      name: NUR
      branch: main



builds:
  - &bin
    id: "helmtide"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goamd64:
      # Go can build using different instruction sets - https://github.com/golang/go/wiki/MinimumRequirements#amd64
      # We don't really need this type of optimization (limiting CPUs helmtide can run on) so we use general v1.
      - v1
    goos:
      - linux
      # - windows
      - darwin
    main: ./cmd/helmtide
    ldflags:
      - -s -w -X github.com/semx/helmtide/pkg/version.Version={{ .Version }}

  #  - <<: *bin
  #    main: ./cmd/schema
  #    id: schema
  #    binary: schema

  - <<: *bin
    main: ./cmd/gitops
    id: gitops
    binary: gitops

###
# Packages
###
archives:
  - &archive
    builds: [ helmtide ]
    name_template: >-2
      {{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
      {{- with .Arm }}v{{ . }}{{ end -}}
      {{- with .Mips }}_{{ . }}{{ end -}}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end -}}
    id: helmtide
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

  - <<: *archive
    id: gitops
    builds: [ gitops ]


nfpms:
  - &nfpms
    id: helmtide
    maintainer: community@helmtide.dev
    builds: [ helmtide ]
    formats:
      - apk
      - deb
      - rpm

  - <<: *nfpms
    id: gitops
    package_name: gitops
    builds: [ gitops ]


checksum:
  name_template: "checksums.txt"

dockers:
  # helmtide
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/semx/helmtide:{{ .Version }}-scratch-amd64
      - ghcr.io/semx/helmtide:scratch-amd64
      - diamon/helmtide:{{ .Version }}-scratch-amd64
      - diamon/helmtide:scratch-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.description=helmtide is a maintained fork of helmwave: release management for helm"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/semx/helmtide"
      - "--label=org.opencontainers.image.url=https://github.com/semx/helmtide/pkgs/container/helmtide"
      - "--label=org.opencontainers.image.documentation=https://helmtide.dev/"

      - "--platform=linux/amd64"
      - "--target=scratch-goreleaser"
      - "--pull"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/semx/helmtide:{{ .Version }}-scratch-arm64v8
      - ghcr.io/semx/helmtide:scratch-arm64v8
      - diamon/helmtide:{{ .Version }}-scratch-arm64v8
      - diamon/helmtide:scratch-arm64v8
    build_flag_templates:
      - "--label=org.opencontainers.image.description=helmtide is a maintained fork of helmwave: release management for helm"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/semx/helmtide"
      - "--label=org.opencontainers.image.url=https://github.com/semx/helmtide/pkgs/container/helmtide"
      - "--label=org.opencontainers.image.documentation=https://helmtide.dev/"

      - "--platform=linux/arm64/v8"
      - "--target=scratch-goreleaser"
      - "--pull"
    goos: linux
    goarch: arm64
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/semx/helmtide:{{ .Version }}-amd64
      - ghcr.io/semx/helmtide:latest-amd64
      - diamon/helmtide:{{ .Version }}-amd64
      - diamon/helmtide:latest-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.description=helmtide is a maintained fork of helmwave: release management for helm"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/semx/helmtide"
      - "--label=org.opencontainers.image.url=https://github.com/semx/helmtide/pkgs/container/helmtide"
      - "--label=org.opencontainers.image.documentation=https://helmtide.dev/"

      - "--platform=linux/amd64"
      - "--target=goreleaser"
      - "--pull"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/semx/helmtide:{{ .Version }}-arm64v8
      - ghcr.io/semx/helmtide:latest-arm64v8
      - diamon/helmtide:{{ .Version }}-arm64v8
      - diamon/helmtide:latest-arm64v8
    build_flag_templates:
      - "--label=org.opencontainers.image.description=helmtide is a maintained fork of helmwave: release management for helm"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/semx/helmtide"
      - "--label=org.opencontainers.image.url=https://github.com/semx/helmtide/pkgs/container/helmtide"
      - "--label=org.opencontainers.image.documentation=https://helmtide.dev/"

      - "--platform=linux/arm64/v8"
      - "--target=goreleaser"
      - "--pull"
    goos: linux
    goarch: arm64
    use: buildx

  # gitops
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmtide/gitops:{{ .Version }}-scratch-amd64
      - ghcr.io/helmtide/gitops:scratch-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.description=GitOps plugin for helmtide"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=gitops"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/semx/helmtide"
      - "--label=org.opencontainers.image.url=https://github.com/semx/helmtide/pkgs/container/gitops"
      - "--label=org.opencontainers.image.documentation=https://helmtide.dev/"

      - "--platform=linux/amd64"
      - "--target=scratch-goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=gitops"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmtide/gitops:{{ .Version }}-scratch-arm64v8
      - ghcr.io/helmtide/gitops:scratch-arm64v8
    build_flag_templates:
      - "--label=org.opencontainers.image.description=GitOps plugin for helmtide"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=gitops"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/semx/helmtide"
      - "--label=org.opencontainers.image.url=https://github.com/semx/helmtide/pkgs/container/gitops"
      - "--label=org.opencontainers.image.documentation=https://helmtide.dev/"

      - "--platform=linux/arm64/v8"
      - "--target=scratch-goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=gitops"
    goos: linux
    goarch: arm64
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmtide/gitops:{{ .Version }}-amd64
      - ghcr.io/helmtide/gitops:latest-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.description=GitOps plugin for helmtide"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=gitops"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/semx/helmtide"
      - "--label=org.opencontainers.image.url=https://github.com/semx/helmtide/pkgs/container/gitops"
      - "--label=org.opencontainers.image.documentation=https://helmtide.dev/"

      - "--platform=linux/amd64"
      - "--target=goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=gitops"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmtide/gitops:{{ .Version }}-arm64v8
      - ghcr.io/helmtide/gitops:latest-arm64v8
    build_flag_templates:
      - "--label=org.opencontainers.image.description=GitOps plugin for helmtide"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=gitops"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/semx/helmtide"
      - "--label=org.opencontainers.image.url=https://github.com/semx/helmtide/pkgs/container/gitops"
      - "--label=org.opencontainers.image.documentation=https://helmtide.dev/"

      - "--platform=linux/arm64/v8"
      - "--target=goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=gitops"
    goos: linux
    goarch: arm64
    use: buildx

docker_manifests:
  # helmtide: GitHub Container Registry
  - name_template: ghcr.io/semx/helmtide:{{ .Version }}-scratch
    image_templates:
      - ghcr.io/semx/helmtide:{{ .Version }}-scratch-amd64
      - ghcr.io/semx/helmtide:{{ .Version }}-scratch-arm64v8
  - name_template: ghcr.io/semx/helmtide:scratch
    image_templates:
      - ghcr.io/semx/helmtide:scratch-amd64
      - ghcr.io/semx/helmtide:scratch-arm64v8
  - name_template: ghcr.io/semx/helmtide:{{ .Version }}
    image_templates:
      - ghcr.io/semx/helmtide:{{ .Version }}-amd64
      - ghcr.io/semx/helmtide:{{ .Version }}-arm64v8
  - name_template: ghcr.io/semx/helmtide:latest
    image_templates:
      - ghcr.io/semx/helmtide:latest-amd64
      - ghcr.io/semx/helmtide:latest-arm64v8

  # gitops: GitHub Container Registry
  - name_template: ghcr.io/helmtide/gitops:{{ .Version }}-scratch
    image_templates:
      - ghcr.io/helmtide/gitops:{{ .Version }}-scratch-amd64
      - ghcr.io/helmtide/gitops:{{ .Version }}-scratch-arm64v8
  - name_template: ghcr.io/helmtide/gitops:scratch
    image_templates:
      - ghcr.io/helmtide/gitops:scratch-amd64
      - ghcr.io/helmtide/gitops:scratch-arm64v8
  - name_template: ghcr.io/helmtide/gitops:{{ .Version }}
    image_templates:
      - ghcr.io/helmtide/gitops:{{ .Version }}-amd64
      - ghcr.io/helmtide/gitops:{{ .Version }}-arm64v8
  - name_template: ghcr.io/helmtide/gitops:latest
    image_templates:
      - ghcr.io/helmtide/gitops:latest-amd64
      - ghcr.io/helmtide/gitops:latest-arm64v8

  # helmtide: DockerHub
  - name_template: diamon/helmtide:{{ .Version }}
    image_templates:
      - diamon/helmtide:{{ .Version }}-amd64
      - diamon/helmtide:{{ .Version }}-arm64v8
  - name_template: diamon/helmtide:latest
    image_templates:
      - diamon/helmtide:latest-amd64
      - diamon/helmtide:latest-arm64v8
  - name_template: diamon/helmtide:{{ .Version }}-scratch
    image_templates:
      - diamon/helmtide:{{ .Version }}-scratch-amd64
      - diamon/helmtide:{{ .Version }}-scratch-arm64v8
  - name_template: diamon/helmtide:scratch
    image_templates:
      - diamon/helmtide:scratch-amd64
      - diamon/helmtide:scratch-arm64v8


###
# Publishes
###

changelog:
  disable: true
  use: github
  sort: asc

  groups:
    - title: "Tests"
      regexp: "^.*\\(tests?\\):.*$"
      order: 0
    - title: "Dependencies"
      regexp: "^.*\\(deps\\):.*$"
      order: 1
    - title: "CI"
      regexp: "^.*\\(ci\\):.*$"
      order: 2
    - title: "New Features"
      regexp: "^feat(\\(.*\\))?:.*$"
      order: 3
    - title: "Bug Fixes"
      regexp: "^fix(\\(.*\\))?:.*$"
      order: 3
    - title: "Linter"
      regexp: "^.*linter.*$"
      order: 4
    - title: "Other"
      order: 999

  filters:
    exclude:
      - "^WIP:"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - typo
      - "^chore"

snapshot:
  version_template: "{{ .Tag }}-next"

release:
  name_template: "v{{ .Version }}"
  #  draft: true
  prerelease: auto

brews:
  - ids: [ helmtide ]
    repository:
      owner: helmtide
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: false
    goamd64: v1
    homepage: https://helmtide.dev/
    description: "helmtide is a maintained fork of helmwave: release management for helm"
    license: MIT
    directory: Formula
    skip_upload: auto

    custom_block: |
      head "https://github.com/semx/helmtide.git", branch: "main"
    test: |
      assert_match version.to_s, shell_output("#{bin/"helmtide"} --version")
    extra_install: |
      generate_completions_from_executable(bin/"helmtide", "completion", shells: [:bash, :zsh])

milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"

report_sizes: true

###
# Announces
###

announce:
  telegram:
    enabled: true
    chat_id: -1001484486010
    message_template: |
      helmtide *{{ replace .Tag "." "\\." }}* is ready\!
      See more: https://github\.com/semx/helmtide/releases/tag/{{ replace .Tag "." "\\." }}
